[package]
name = "onnx-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
tokenizers = "0.19.1"
ort = { version = "2.0.0-rc.2", features = ["coreml"] }
ndarray = "0.15.6"
num-traits = "0.2.18"
log = "0.4.21"
rand = "0.8.5"
hound = "3.5.1"
tokio = { version = "1.37.0", features = ["full"] }
indicatif = "0.17.8"
directories = "5.0"
reqwest = { version = "0.12.4", features = ["stream"] }
futures-util = "0.3.30"
